# CMake generated Testfile for 
# Source directory: /home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao
# Build directory: /home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(diagnostics_record_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/diagnostics_record_test")
set_tests_properties(diagnostics_record_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(debug_renderer_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/debug_renderer_test")
set_tests_properties(debug_renderer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(timing_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/timing_test")
set_tests_properties(timing_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(observability_integration_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/observability_integration_test")
set_tests_properties(observability_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(temporal_stabilizer_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/temporal_stabilizer_test")
set_tests_properties(temporal_stabilizer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(display_history_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/display_history_test")
set_tests_properties(display_history_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(temporal_integration_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/temporal_integration_test")
set_tests_properties(temporal_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(block3_contract_regression_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/block3_contract_regression_test")
set_tests_properties(block3_contract_regression_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(assignment_completion_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/assignment_completion_test")
set_tests_properties(assignment_completion_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(corner_edge_fit_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/corner_edge_fit_test")
set_tests_properties(corner_edge_fit_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(config_contract_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/config_contract_test")
set_tests_properties(config_contract_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(config_error_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/config_error_test")
set_tests_properties(config_error_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(config_roundtrip_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/config_roundtrip_test")
set_tests_properties(config_roundtrip_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(detector_contract_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/detector_contract_test")
set_tests_properties(detector_contract_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(geometry_model_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/geometry_model_test")
set_tests_properties(geometry_model_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(geometry_utils_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/geometry_utils_test")
set_tests_properties(geometry_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(geometry_matcher_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/geometry_matcher_test")
set_tests_properties(geometry_matcher_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(manual_validation_check "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/manual_validation_check")
set_tests_properties(manual_validation_check PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(corner_resolver_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/corner_resolver_test")
set_tests_properties(corner_resolver_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(screen_order_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/screen_order_test")
set_tests_properties(screen_order_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(semantic_resolver_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/semantic_resolver_test")
set_tests_properties(semantic_resolver_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(detection_validator_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/detection_validator_test")
set_tests_properties(detection_validator_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(geometry_l_topology_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/geometry_l_topology_test")
set_tests_properties(geometry_l_topology_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(geometry_anchor_evidence_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/geometry_anchor_evidence_test")
set_tests_properties(geometry_anchor_evidence_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
add_test(path_a_competition_test "/home/tushenghao/projects/campus-marker-opencv-assignment/build/final-fixes-path-a-release/path_a_competition_test")
set_tests_properties(path_a_competition_test PROPERTIES  _BACKTRACE_TRIPLES "/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;90;add_test;/home/tushenghao/projects/campus-marker-opencv-assignment/src/tushenghao/CMakeLists.txt;0;")
